@startuml
left to right direction
skinparam shadowing false
skinparam linetype ortho
skinparam objectAttributeIconSize 0
skinparam nodesep 45
skinparam ranksep 45
title Example - Queue Configuration

object "External Agenda A" as EA {
  source = System X
}
object "External Agenda B" as EB {
  source = System Y
}
object "Agenda A" as A
object "Agenda B" as B
object "Queue 1" as Q1 {
  policy = BY_APPOINTMENT
}
object "Queue 2" as Q2 {
  policy = BY_ARRIVAL
}

EA --> A
EB --> B
A --> Q1
A --> Q2
B --> Q2
@enduml
